name: Labelmania
on:
  pull_request:
    types: [labeled, unlabeled]
    
jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: echo to matrix putput
        run: echo "matrix=$( echo [ ${{ join(github.event.pull_request.labels.*.name, ',') }} ] )" >> $GITHUB_OUTPUT
    
  echo:
    runs-on: ubuntu-latest
    needs: generate-matrix
  
    strategy:
      matrix:
        label: ${{needs.generate-matrix.outputs.matrix}}

    steps:
      - name: Echo
        run: echo ${{ matrix.label }}
