name: Labelmania
on:
  pull_request:
    types: [labeled, unlabeled]
    
jobs:
  build:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        label: [ ${{ join(github.event.pull_request.labels.*.name, ',') }} ]

    steps:
      - name: Echo
        run: echo ${{ matrix.label }}
