name: Labels

on:
  pull_request:
    types: [labeled, unlabeled]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo ${{ join(github.event.pull_request.labels.*.name, ',') }}
